language: csharp
solution: ./CarWorkshopSystem/CarWorkshopSystem.sln

install:
  - sudo apt-get install nunit-console
  - nuget restore ./CarWorkshopSystem/CarWorkshopSystem.sln
  
script:
  - xbuild ./CarWorkshopSystem/CarWorkshopSystem.sln
